apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-nisary-deploy
  #namespace: dev
  labels:
    app: bankapp-nisary-app-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankapp-nisary-app
  template:
    metadata:
      labels:
        app: bankapp-nisary-app
    spec:
      containers:
      - name: bankapp-nisary-container
        image: nisary123/bankingfinance-img:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-nisary-np-service
  #namespace: dev
  labels:
    app: bankapp-nisary-app
spec:
  selector:
    app: bankapp-nisary-app
  type: NodePort
  ports:
  - nodePort: 31030  
    port: 8082
    targetPort: 8082
